# -*- coding: utf-8 -*-
"""preprocessing_splitting_words

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uWH4z5jzQBhFsIBvHgWFgHvK3hzpUwsK
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive')

imdb = pd.read_csv("/content/gdrive/My Drive/MMA/MGSC661/IMDB_data_Fall_2023.csv")

imdb

"""genres preprocessing"""

genres = imdb["genres"].to_numpy()

unique_genres = []
for i in range(imdb.shape[0]):
  lst = genres[i].split("|")
  for genre in lst:
    if genre in unique_genres:
      continue
    else:
      unique_genres.append(genre)

"""plot preprocessing"""

plot = imdb["plot_keywords"].to_numpy()

movie_idx = imdb.index.to_numpy()

all_row = []
for i in range(imdb.shape[0]):
  lst = plot[i].split("|")
  for word in lst:
    row = [movie_idx[i], word]
    all_row.append(row)

mimic = pd.DataFrame(all_row, columns=["movie", "word"])

mimic

mimic.to_csv("pre_plot.csv")